### ISSUE TITLE
problems about gcn

### ISSUE THREAD

**Issue by maxwellyin** [TeamLab/bert-gcn-for-paper-citation#3]
Hi,
I've cloned the repo and when I ran gcn_pretrain.py, I found that there is no file called GCN.code.gcn_train or  GCN.code.config. I also looked through the original gae repo by tkipf, but I failed to find these file. So where can I get these files?

Looking forward to your reply.
Thanks.

**Comment by janguck** [comment]
I reflected in pull requests. 
you can also check it out at https://github.com/janguck/bert-gcn-for-paper-citation.

**Comment by maxwellyin** [comment]
Oh, got it.
Thanks.
